#!/usr/bin/env python3
"""
从 contracts/schemas/*.yaml 生成三端类型文件（Python / TypeScript / Go）。

用法:
    python scripts/generate_contracts.py
    make generate
"""

import sys
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# 路径配置
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = ROOT / "contracts" / "schemas"

OUTPUT_MAP = {
    "event-types": {
        "python": ROOT / "agentend" / "src" / "generated" / "events.py",
        "typescript": ROOT / "frontend" / "src" / "generated" / "events.ts",
        "go": ROOT / "backend" / "internal" / "generated" / "events.go",
    },
    "agent-request": {
        "python": ROOT / "agentend" / "src" / "generated" / "request.py",
        "typescript": ROOT / "frontend" / "src" / "generated" / "request.ts",
        "go": ROOT / "backend" / "internal" / "generated" / "request.go",
    },
    "agent-response": {
        "python": ROOT / "agentend" / "src" / "generated" / "response.py",
        "typescript": ROOT / "frontend" / "src" / "generated" / "response.ts",
        "go": ROOT / "backend" / "internal" / "generated" / "response.go",
    },
    "agent-routing": {
        "python": ROOT / "agentend" / "src" / "generated" / "agent_routing.py",
        "typescript": ROOT / "frontend" / "src" / "generated" / "agent-routing.ts",
        "go": ROOT / "backend" / "internal" / "generated" / "agent_routing.go",
    },
    "session-state": {
        "python": ROOT / "agentend" / "src" / "generated" / "session.py",
        "typescript": ROOT / "frontend" / "src" / "generated" / "session.ts",
        "go": ROOT / "backend" / "internal" / "generated" / "session.go",
    },
    "message": {
        "python": ROOT / "agentend" / "src" / "generated" / "message.py",
        "typescript": ROOT / "frontend" / "src" / "generated" / "message.ts",
        "go": ROOT / "backend" / "internal" / "generated" / "message.go",
    },
    "validate-repo-path": {
        "python": ROOT / "agentend" / "src" / "generated" / "validate_repo_path.py",
        "typescript": ROOT / "frontend" / "src" / "generated" / "validate-repo-path.ts",
        "go": ROOT / "backend" / "internal" / "generated" / "validate_repo_path.go",
    },
}

GEN_HEADER = "Code generated by make generate. DO NOT EDIT."


# ---------------------------------------------------------------------------
# 工具函数
# ---------------------------------------------------------------------------
def load_schema(name: str) -> dict:
    path = SCHEMAS_DIR / f"{name}.yaml"
    with open(path) as f:
        return yaml.safe_load(f)


def pascal(s: str) -> str:
    """kebab-case / snake_case → PascalCase。"""
    return "".join(w.capitalize() for w in s.replace("-", "_").split("_"))


def go_field(name: str) -> str:
    """snake_case → Go 导出字段名。"""
    return "".join(w.capitalize() for w in name.split("_"))


def py_enum_member(val: str) -> str:
    """枚举值 → Python 合法的 UPPER_SNAKE_CASE 标识符。"""
    return val.upper().replace("-", "_")


# ---------------------------------------------------------------------------
# Python 生成器
# ---------------------------------------------------------------------------
def gen_python(schema: dict, name: str) -> str:
    lines = [
        f"# {GEN_HEADER}",
        "",
        "from enum import Enum",
        "from typing import Any, Optional",
        "",
        "from pydantic import BaseModel, Field",
        "",
    ]

    for def_name, defn in schema.get("definitions", {}).items():
        if defn.get("type") == "string" and "enum" in defn:
            lines.append(f"class {def_name}(str, Enum):")
            for val in defn["enum"]:
                member = py_enum_member(val)
                lines.append(f'    {member} = "{val}"')
            lines.append("")
        elif defn.get("type") == "object":
            lines.append(f"class {def_name}(BaseModel):")
            props = defn.get("properties", {})
            required = set(defn.get("required", []))

            if not props:
                lines.append("    pass")
                lines.append("")
                continue

            for prop_name, prop in props.items():
                ann = _py_type(prop, schema)
                default = _py_default(prop, prop_name, required, schema)
                lines.append(f"    {prop_name}: {ann}{default}")
            lines.append("")

    return "\n".join(lines)


def _py_type(prop: dict, schema: dict) -> str:
    ref = prop.get("$ref", "")
    if ref:
        return ref.split("/")[-1]

    ptype = prop.get("type")
    if isinstance(ptype, list):
        non_null = [t for t in ptype if t != "null"]
        if len(non_null) == 1:
            inner = {"string": "str", "number": "float", "boolean": "bool"}.get(non_null[0], "Any")
            return f"Optional[{inner}]"
        return "Any"

    return {
        "string": "str",
        "number": "float",
        "boolean": "bool",
        "array": "list[Any]",
        "object": "dict[str, Any]",
    }.get(ptype, "Any")


def _py_default(prop: dict, name: str, required: set, schema: dict) -> str:
    ref = prop.get("$ref", "")
    if name not in required:
        if "default" in prop:
            dv = prop["default"]
            if isinstance(dv, bool):
                return f" = {dv}"
            if isinstance(dv, str):
                # 如果有 $ref，说明默认值是枚举成员
                if ref:
                    ref_name = ref.split("/")[-1]
                    return f" = {ref_name}.{py_enum_member(dv)}"
                return f' = "{dv}"'
            return f" = {dv!r}"
        if ref:
            return " = None"
        return " = None"
    return ""


# ---------------------------------------------------------------------------
# TypeScript 生成器
# ---------------------------------------------------------------------------
def gen_typescript(schema: dict, name: str) -> str:
    lines = [f"// {GEN_HEADER}", ""]

    for def_name, defn in schema.get("definitions", {}).items():
        if defn.get("type") == "string" and "enum" in defn:
            vals = " | ".join(f'"{v}"' for v in defn["enum"])
            lines.append(f"export type {def_name} = {vals};")
            lines.append("")
            lines.append(f"export const {def_name}Values = {{")
            for v in defn["enum"]:
                lines.append(f'  {pascal(v)}: "{v}" as const,')
            lines.append("} as const;")
            lines.append("")
        elif defn.get("type") == "object":
            lines.append(f"export interface {def_name} {{")
            props = defn.get("properties", {})
            required = set(defn.get("required", []))

            for prop_name, prop in props.items():
                ts_type = _ts_type(prop, schema)
                opt = "" if prop_name in required else "?"
                lines.append(f"  {prop_name}{opt}: {ts_type};")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def _ts_type(prop: dict, schema: dict) -> str:
    ref = prop.get("$ref", "")
    if ref:
        return ref.split("/")[-1]

    ptype = prop.get("type")
    if isinstance(ptype, list):
        non_null = [t for t in ptype if t != "null"]
        if len(non_null) == 1:
            inner = {"string": "string", "number": "number", "boolean": "boolean"}.get(non_null[0], "unknown")
            return f"{inner} | null"
        return "unknown"

    if ptype == "string":
        return "string"
    if ptype == "number":
        return "number"
    if ptype == "boolean":
        return "boolean"
    if ptype == "array":
        items_type = _ts_type(prop.get("items", {}), schema)
        return f"{items_type}[]"
    if ptype == "object":
        return "Record<string, unknown>"
    return "unknown"


# ---------------------------------------------------------------------------
# Go 生成器
# ---------------------------------------------------------------------------
def gen_go(schema: dict, name: str) -> str:
    lines = [f"// {GEN_HEADER}", "", "package generated", ""]

    for def_name, defn in schema.get("definitions", {}).items():
        if defn.get("type") == "string" and "enum" in defn:
            lines.append(f"type {def_name} string")
            lines.append("")
            lines.append("const (")
            for val in defn["enum"]:
                const_name = f"{def_name}{pascal(val)}"
                lines.append(f'\t{const_name} {def_name} = "{val}"')
            lines.append(")")
            lines.append("")
        elif defn.get("type") == "object":
            lines.append(f"type {def_name} struct {{")
            props = defn.get("properties", {})
            required = set(defn.get("required", []))

            for prop_name, prop in props.items():
                go_type = _go_type(prop, schema)
                field_name = go_field(prop_name)
                json_tag = prop_name
                if prop_name not in required:
                    json_tag += ",omitempty"
                lines.append(f"\t{field_name} {go_type} `json:\"{json_tag}\"`")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def _go_type(prop: dict, schema: dict) -> str:
    ref = prop.get("$ref", "")
    if ref:
        return ref.split("/")[-1]

    ptype = prop.get("type")
    if isinstance(ptype, list):
        non_null = [t for t in ptype if t != "null"]
        if len(non_null) == 1:
            inner = {"string": "string", "number": "float64", "boolean": "bool"}.get(non_null[0], "interface{}")
            return f"*{inner}"
        return "interface{}"

    if ptype == "string":
        return "string"
    if ptype == "number":
        return "float64"
    if ptype == "boolean":
        return "bool"
    if ptype == "array":
        items_type = _go_type(prop.get("items", {}), schema)
        return f"[]{items_type}"
    if ptype == "object":
        return "map[string]interface{}"
    return "interface{}"


# ---------------------------------------------------------------------------
# 主流程
# ---------------------------------------------------------------------------
def main() -> None:
    if not SCHEMAS_DIR.exists():
        print(f"Error: {SCHEMAS_DIR} not found", file=sys.stderr)
        sys.exit(1)

    generators = {
        "python": gen_python,
        "typescript": gen_typescript,
        "go": gen_go,
    }

    for schema_name, outputs in OUTPUT_MAP.items():
        schema = load_schema(schema_name)
        for lang, out_path in outputs.items():
            out_path.parent.mkdir(parents=True, exist_ok=True)
            content = generators[lang](schema, schema_name)
            out_path.write_text(content + "\n")
            print(f"  generated: {out_path.relative_to(ROOT)}")

    print("Done.")


if __name__ == "__main__":
    main()
